In [10]:
import numpy as np
import nibabel
import os
import loader_helper

In [2]:
path = '/home/localadmin/segthor/data/train_resampled'

In [3]:
series = os.listdir(path)
print(series)

['Patient_24', 'Patient_15', 'Patient_32', 'Patient_19', 'Patient_29', 'Patient_07', 'Patient_28', 'Patient_14', 'Patient_13', 'Patient_26', 'Patient_25', 'Patient_21', 'Patient_30', 'Patient_10', 'Patient_38', 'Patient_03', 'Patient_34', 'Patient_16', 'Patient_33', 'Patient_09', 'Patient_02', 'Patient_35', 'Patient_31', 'Patient_40', 'Patient_11', 'Patient_01', 'Patient_12', 'Patient_18', 'Patient_17', 'Patient_37', 'Patient_23', 'Patient_22', 'Patient_39', 'Patient_27', 'Patient_04', 'Patient_36', 'Patient_06', 'Patient_20', 'Patient_08', 'Patient_05']


In [11]:
border = 64
for s in series:
    image = loader_helper.read_nii(os.path.join(path, s, 'GT.nii.gz'))
    bboxes = []
    for i in range(5):
        bboxes.append(loader_helper.bbox3(image==i))
        
    bbox = bboxes[0]
    bbox[0] = bbox[0] - 64
    bbox[1] = bbox[1] + 64
    
    for b in bboxes:
        b[0] = b[0] - border
        b[1] = b[1] + border
        
        bbox[0] = np.maximum(bbox[0], b[0])
        bbox[1] = np.minimum(bbox[1], b[1])
        
    print(s, bbox)

Patient_24 [[185 121  94]
 [362 305 218]]
Patient_15 [[156 123  62]
 [337 308 182]]
Patient_32 [[161 161  83]
 [336 343 200]]
Patient_19 [[145 132  76]
 [321 340 187]]
Patient_29 [[177 204  98]
 [342 385 225]]
Patient_07 [[172 154  72]
 [346 318 198]]
Patient_28 [[184 154 133]
 [350 339 256]]
Patient_14 [[185 162  78]
 [355 347 187]]
Patient_13 [[174 156  53]
 [342 319 176]]
Patient_26 [[172 138  97]
 [342 305 210]]
Patient_25 [[173 165  56]
 [349 339 182]]
Patient_21 [[164 125  69]
 [336 325 186]]
Patient_30 [[177 200 101]
 [340 395 217]]
Patient_10 [[172 141  43]
 [339 297 164]]
Patient_38 [[167 150  78]
 [349 336 197]]
Patient_03 [[165 178  43]
 [342 353 162]]
Patient_34 [[171 134 108]
 [358 317 227]]
Patient_16 [[169 159  78]
 [333 330 205]]
Patient_33 [[173 137  56]
 [341 306 177]]
Patient_09 [[170 147  41]
 [338 330 168]]
Patient_02 [[160 144 194]
 [336 316 312]]
Patient_35 [[262 275  35]
 [427 435 158]]
Patient_31 [[166 198  48]
 [339 354 175]]
Patient_40 [[168 169 104]
 [343 33